# Web Of Science

In [ ]:
import os
import pandas as pd

queries_path = "./Relation_low_resources/queries.csv"

df = pd.read_csv(queries_path)
df.head()

,Query ID,Description,Query String
0,Q1,"Relation Extraction, Low-resource","""Relation Extraction"" AND ""Low-resource"""
1,Q2,"Relation Extraction, Data scarcity","""Relation Extraction"" AND ""Data scarcity"""
2,Q3,"Relation Extraction, Limited data","""Relation Extraction"" AND ""Limited data"""
3,Q4,"Relation Extraction, Sparse data","""Relation Extraction"" AND ""Sparse data"""
4,Q16,"Triplet Extraction, Low-resource","""Triplet Extraction"" AND ""Low-resource"""

In [3]:
queries = df["Query String"]
print(queries)

0         "Relation Extraction" AND "Low-resource"
1        "Relation Extraction" AND "Data scarcity"
2         "Relation Extraction" AND "Limited data"
3          "Relation Extraction" AND "Sparse data"
4          "Triplet Extraction" AND "Low-resource"
5         "Triplet Extraction" AND "Data scarcity"
6          "Triplet Extraction" AND "Limited data"
7           "Triplet Extraction" AND "Sparse data"
8      "Information Extraction" AND "Low-resource"
9     "Information Extraction" AND "Data scarcity"
10     "Information Extraction" AND "Limited data"
11      "Information Extraction" AND "Sparse data"
12        "Relation Generation" AND "Low-resource"
13       "Relation Generation" AND "Data scarcity"
14        "Relation Generation" AND "Limited data"
15         "Relation Generation" AND "Sparse data"
16         "Triplet Generation" AND "Low-resource"
17        "Triplet Generation" AND "Data scarcity"
18         "Triplet Generation" AND "Limited data"
19          "Triplet Generation" AND "Sparse data"
Name: Query String, dtype: object

In [4]:
import pandas as pd

# Suponiendo que la columna "Description" contiene cadenas como:
# "Relation Extraction, Low-resource"
terms = df["Description"].tolist()

# Dividir cada descripción en dos términos y eliminar espacios extra
pairs = [tuple(map(str.strip, term.split(','))) for term in terms if ',' in term]

# Crear el DataFrame con dos columnas a partir de la lista de tuplas
terms_df = pd.DataFrame(pairs, columns=["term1", "term2"])

display(terms_df)

                     term1          term2
0      Relation Extraction   Low-resource
1      Relation Extraction  Data scarcity
2      Relation Extraction   Limited data
3      Relation Extraction    Sparse data
4       Triplet Extraction   Low-resource
5       Triplet Extraction  Data scarcity
6       Triplet Extraction   Limited data
7       Triplet Extraction    Sparse data
8   Information Extraction   Low-resource
9   Information Extraction  Data scarcity
10  Information Extraction   Limited data
11  Information Extraction    Sparse data
12     Relation Generation   Low-resource
13     Relation Generation  Data scarcity
14     Relation Generation   Limited data
15     Relation Generation    Sparse data
16      Triplet Generation   Low-resource
17      Triplet Generation  Data scarcity
18      Triplet Generation   Limited data
19      Triplet Generation    Sparse data

# Manual

In [5]:
!pip install xlrd

Requirement already satisfied: xlrd in /Users/jpardo/anaconda3/lib/python3.11/site-packages (2.0.1)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip

In [6]:
import os 
import pandas as pd

def load_all_datasets(main_path, queque, dataset):
    scopus = pd.DataFrame()
    que = os.listdir(main_path)
    for i in que:
        # Saltar elementos que terminen en .csv o .ipynb o sean ".DS_Store"
        if i.endswith('.csv') or i.endswith('.ipynb') or i == ".DS_Store" or i in queque:
            continue
        p = os.path.join(main_path, i)
        que2 = os.listdir(p)
        for a in que2:
            if a.endswith('.csv') or a.endswith('.ipynb') or a == ".DS_Store":
                continue
            dat = os.path.join(p, a)
            que3 = os.listdir(dat)
            if que3:
                ar = os.path.join(dat, dataset)
                if dataset.endswith(".xls"):
                    r = pd.read_excel(ar, engine="xlrd")
                    r["query"]=i
                else:
                    r = pd.read_csv(ar)
                    r["query"]=i
                scopus = pd.concat([scopus, r], ignore_index=True)
    return scopus

In [ ]:
# Ejemplo de uso:
main_path = "./" #/web_of_science
wos = load_all_datasets(main_path, queque=[], dataset="savedrecs.xls")
display(wos)

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record,query
0,C,"Bhavya, B; Isaza, PT; Deng, Y; Nidd, M; Azad, ...",NaN,"Pedrycz, W; Wang, J; He, Y; Dinh, TN; Grant, C...",NaN,"Bhavya, Bhavya; Isaza, Paulina Toro; Deng, Yu;...",NaN,NaN,Exploring Large Language Models for Low-Resour...,2023 23RD IEEE INTERNATIONAL CONFERENCE ON DAT...,...,Computer Science,BW5OA,NaN,NaN,NaN,NaN,2025-03-10,WOS:001164077500148,0,q31
1,C,"Cai, E; Simek, O; Miller, BA; Sullivan, D; You...",NaN,"Botta, F; Macedo, M; Barbosa, H; Menezes, R",NaN,"Cai, Erica; Simek, Olga; Miller, Benjamin A.; ...",NaN,NaN,From Low Resource Information Extraction to Id...,"COMPLEX NETWORKS XV, COMPLENET 2024",...,Computer Science,BX2MU,NaN,NaN,NaN,NaN,2025-03-10,WOS:001265068200002,0,q31
2,C,"Li, TL; Wang, ZX; Li, ZJ",NaN,"Williams, B; Chen, Y; Neville, J",NaN,"Li, Tongliang; Wang, Zixiang; Li, Zhoujun",NaN,NaN,Low Resource Quantitative Information Extracti...,THIRTY-SEVENTH AAAI CONFERENCE ON ARTIFICIAL I...,...,Computer Science,BX1FC,NaN,NaN,NaN,NaN,2025-03-10,WOS:001243753000066,0,q31
3,J,"Ariyanto, ADP; Purwitasari, D; Fatichah, C",NaN,NaN,NaN,"Ariyanto, Amelia Devi Putri; Purwitasari, Dian...",NaN,NaN,A Systematic Review on Semantic Role Labeling ...,IEEE ACCESS,...,Computer Science; Engineering; Telecommunications,OQ9A1,NaN,gold,NaN,NaN,2025-03-10,WOS:001208844900001,0,q31
4,C,"Ma, MD; Wang, XX; Kung, PN; Brantingham, PJ; P...",NaN,"Wooldridge, M; Dy, J; Natarajan, S",NaN,"Ma, Mingyu Derek; Wang, Xiaoxuan; Kung, Po-Nie...",NaN,NaN,STAR: Boosting Low-Resource Information Extrac...,THIRTY-EIGHTH AAAI CONFERENCE ON ARTIFICIAL IN...,...,Computer Science; Education & Educational Rese...,BX0WL,NaN,NaN,NaN,NaN,2025-03-10,WOS:001239407300029,0,q31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,J,"Moscato, V; Napolano, G; Postiglione, M; Sperl...",NaN,NaN,NaN,"Moscato, Vincenzo; Napolano, Giuseppe; Postigl...",NaN,NaN,Multi-task learning for few-shot biomedical re...,ARTIFICIAL INTELLIGENCE REVIEW,...,Computer Science,S4WT3,NaN,hybrid,NaN,NaN,2025-03-10,WOS:000970223600001,0,q3
116,C,"Stickley, D",NaN,NaN,ASSOC COMPUTAT LINGUIST,"Stickley, Daniel",NaN,NaN,Relating Relations: Meta-Relation Extraction f...,EACL 2021: THE 16TH CONFERENCE OF THE EUROPEAN...,...,Computer Science; Linguistics,BT9HU,NaN,NaN,NaN,NaN,2025-03-10,WOS:000861067300018,0,q3
117,J,"Gao, F; Song, XR; Gu, JG; Zhang, LH; Liu, Y; Z...",NaN,NaN,NaN,"Gao, Feng; Song, Xuren; Gu, Jinguang; Zhang, L...",NaN,NaN,Fine-Grained Relation Extraction for Drug Inst...,IEEE ACCESS,...,Computer Science; Engineering; Telecommunications,I8YS2,NaN,gold,NaN,NaN,2025-03-10,WOS:001005589400001,0,q3
118,C,"Zheng, YD; Anran, H; Tuan, LA",NaN,"Rogers, A; Boyd-Graber, J; Okazaki, N",NaN,"Zheng Yandan; Anran, Hao; Tuan, Luu Anh",NaN,NaN,Jointprop: Joint Semi-supervised Learning for ...,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,...,Computer Science,BW7IT,NaN,NaN,NaN,NaN,2025-03-10,WOS:001190962506018,0,q3
119,J,"Tong, YT; Tong, JJ; Xia, SD; Zhou, QL; Shen, YQ",NaN,NaN,NaN,"Tong, Yetao; Tong, Jijun; Xia, Shudong; Zhou, ...",NaN,NaN,CECRel: A joint entity and relation extraction...,JOURNAL OF BIOMEDICAL INFORMATICS,...,Computer Science; Medical Informatics,Y9G8X,40010480.0,NaN,NaN,NaN,2025-03-10,WOS:001435127300001,0,q3

In [8]:
import pandas as pd

# Supón que ya tienes el DataFrame 'df'
initial_rows = wos.shape[0]  # Número de filas inicial

# Eliminar filas duplicadas (puedes usar inplace=True para modificar el mismo DataFrame)
wos_final = wos.drop_duplicates(subset='Article Title', keep='first')

final_rows = wos_final.shape[0]  # Número de filas después de eliminar duplicados

filas_eliminadas = initial_rows - final_rows

print(f"Se han eliminado {filas_eliminadas} filas duplicadas.")

Se han eliminado 23 filas duplicadas.

In [9]:
ruta=os.path.join(main_path, "wos.csv")
wos_final.to_csv(ruta)

In [ ]:
# Ejemplo de uso:
main_path = "./" #/web_of_science
wos2 = load_all_datasets(main_path, ['q31','q32','q33','q34','q46','q47','q48','q49','q61','q62','q63','q64'], dataset="savedrecs.xls")
display(wos2)

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record,query
0,C,"Zhou, WX; Zhang, S; Naumann, T; Chen, MH; Poon, H",NaN,"Rogers, A; Boyd-Graber, J; Okazaki, N",NaN,"Zhou, Wenxuan; Zhang, Sheng; Naumann, Tristan;...",NaN,NaN,Continual Contrastive Finetuning Improves Low-...,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,...,Computer Science,BW7IT,NaN,NaN,NaN,NaN,2025-03-10,WOS:001190962505001,0,q1
1,C,"Hu, XM; Zhang, CW; Yang, YW; Li, XH; Lin, L; W...",NaN,NaN,Assoc Computat Linguist,"Hu, Xuming; Zhang, Chenwei; Yang, Yawen; Li, X...",NaN,NaN,Gradient Imitation Reinforcement Learning for ...,2021 CONFERENCE ON EMPIRICAL METHODS IN NATURA...,...,Computer Science; Linguistics,BT8XM,NaN,NaN,NaN,NaN,2025-03-10,WOS:000855966302075,0,q1
2,J,"Wu, XP; Hu, J; Wan, WJ; Zhang, BX; Li, CJ",NaN,NaN,NaN,"Wu, Xiangping; Hu, Jun; Wan, Wangjun; Zhang, B...",NaN,NaN,Incentive Instruction for Event Relation Extra...,IEEE ACCESS,...,Computer Science; Engineering; Telecommunications,WQ0O6,NaN,gold,NaN,NaN,2025-03-10,WOS:001256223200001,0,q1
3,J,"Guo, Q; Guo, Y; Zhao, J",NaN,NaN,NaN,"Guo, Qian; Guo, Yi; Zhao, Jin",NaN,NaN,HRCL: Hierarchical Relation Contrastive Learni...,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,...,Computer Science; Engineering,PL6F5,38683710.0,NaN,NaN,NaN,2025-03-10,WOS:001214266300001,0,q1
4,C,"Yu, JJ; Wang, X; Chen, WL",NaN,"Wooldridge, M; Dy, J; Natarajan, S",NaN,"Yu, Junjie; Wang, Xing; Chen, Wenliang",NaN,NaN,Reliable Data Generation and Selection for Low...,THIRTY-EIGHTH AAAI CONFERENCE ON ARTIFICIAL IN...,...,Computer Science; Education & Educational Rese...,BX0WL,NaN,NaN,NaN,NaN,2025-03-10,WOS:001239407300105,0,q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,J,"Moscato, V; Napolano, G; Postiglione, M; Sperl...",NaN,NaN,NaN,"Moscato, Vincenzo; Napolano, Giuseppe; Postigl...",NaN,NaN,Multi-task learning for few-shot biomedical re...,ARTIFICIAL INTELLIGENCE REVIEW,...,Computer Science,S4WT3,NaN,hybrid,NaN,NaN,2025-03-10,WOS:000970223600001,0,q3
75,C,"Stickley, D",NaN,NaN,ASSOC COMPUTAT LINGUIST,"Stickley, Daniel",NaN,NaN,Relating Relations: Meta-Relation Extraction f...,EACL 2021: THE 16TH CONFERENCE OF THE EUROPEAN...,...,Computer Science; Linguistics,BT9HU,NaN,NaN,NaN,NaN,2025-03-10,WOS:000861067300018,0,q3
76,J,"Gao, F; Song, XR; Gu, JG; Zhang, LH; Liu, Y; Z...",NaN,NaN,NaN,"Gao, Feng; Song, Xuren; Gu, Jinguang; Zhang, L...",NaN,NaN,Fine-Grained Relation Extraction for Drug Inst...,IEEE ACCESS,...,Computer Science; Engineering; Telecommunications,I8YS2,NaN,gold,NaN,NaN,2025-03-10,WOS:001005589400001,0,q3
77,C,"Zheng, YD; Anran, H; Tuan, LA",NaN,"Rogers, A; Boyd-Graber, J; Okazaki, N",NaN,"Zheng Yandan; Anran, Hao; Tuan, Luu Anh",NaN,NaN,Jointprop: Joint Semi-supervised Learning for ...,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,...,Computer Science,BW7IT,NaN,NaN,NaN,NaN,2025-03-10,WOS:001190962506018,0,q3
78,J,"Tong, YT; Tong, JJ; Xia, SD; Zhou, QL; Shen, YQ",NaN,NaN,NaN,"Tong, Yetao; Tong, Jijun; Xia, Shudong; Zhou, ...",NaN,NaN,CECRel: A joint entity and relation extraction...,JOURNAL OF BIOMEDICAL INFORMATICS,...,Computer Science; Medical Informatics,Y9G8X,40010480.0,NaN,NaN,NaN,2025-03-10,WOS:001435127300001,0,q3

In [11]:
import pandas as pd

# Supón que ya tienes el DataFrame 'df'
initial_rows = wos2.shape[0]  # Número de filas inicial

# Eliminar filas duplicadas (puedes usar inplace=True para modificar el mismo DataFrame)
wos_final2 = wos2.drop_duplicates(subset='Article Title', keep='first')
# wos_final = wos.drop_duplicates()

final_rows = wos_final2.shape[0]  # Número de filas después de eliminar duplicados

filas_eliminadas = initial_rows - final_rows

print(f"Se han eliminado {filas_eliminadas} filas duplicadas.")

Se han eliminado 17 filas duplicadas.

In [12]:
wos_final2.to_csv(os.path.join(main_path, "wos_reducido.csv"))

In [13]:
display(wos_final2)

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record,query
0,C,"Zhou, WX; Zhang, S; Naumann, T; Chen, MH; Poon, H",NaN,"Rogers, A; Boyd-Graber, J; Okazaki, N",NaN,"Zhou, Wenxuan; Zhang, Sheng; Naumann, Tristan;...",NaN,NaN,Continual Contrastive Finetuning Improves Low-...,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,...,Computer Science,BW7IT,NaN,NaN,NaN,NaN,2025-03-10,WOS:001190962505001,0,q1
1,C,"Hu, XM; Zhang, CW; Yang, YW; Li, XH; Lin, L; W...",NaN,NaN,Assoc Computat Linguist,"Hu, Xuming; Zhang, Chenwei; Yang, Yawen; Li, X...",NaN,NaN,Gradient Imitation Reinforcement Learning for ...,2021 CONFERENCE ON EMPIRICAL METHODS IN NATURA...,...,Computer Science; Linguistics,BT8XM,NaN,NaN,NaN,NaN,2025-03-10,WOS:000855966302075,0,q1
2,J,"Wu, XP; Hu, J; Wan, WJ; Zhang, BX; Li, CJ",NaN,NaN,NaN,"Wu, Xiangping; Hu, Jun; Wan, Wangjun; Zhang, B...",NaN,NaN,Incentive Instruction for Event Relation Extra...,IEEE ACCESS,...,Computer Science; Engineering; Telecommunications,WQ0O6,NaN,gold,NaN,NaN,2025-03-10,WOS:001256223200001,0,q1
3,J,"Guo, Q; Guo, Y; Zhao, J",NaN,NaN,NaN,"Guo, Qian; Guo, Yi; Zhao, Jin",NaN,NaN,HRCL: Hierarchical Relation Contrastive Learni...,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,...,Computer Science; Engineering,PL6F5,38683710.0,NaN,NaN,NaN,2025-03-10,WOS:001214266300001,0,q1
4,C,"Yu, JJ; Wang, X; Chen, WL",NaN,"Wooldridge, M; Dy, J; Natarajan, S",NaN,"Yu, Junjie; Wang, Xing; Chen, Wenliang",NaN,NaN,Reliable Data Generation and Selection for Low...,THIRTY-EIGHTH AAAI CONFERENCE ON ARTIFICIAL IN...,...,Computer Science; Education & Educational Rese...,BX0WL,NaN,NaN,NaN,NaN,2025-03-10,WOS:001239407300105,0,q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,J,"Moscato, V; Napolano, G; Postiglione, M; Sperl...",NaN,NaN,NaN,"Moscato, Vincenzo; Napolano, Giuseppe; Postigl...",NaN,NaN,Multi-task learning for few-shot biomedical re...,ARTIFICIAL INTELLIGENCE REVIEW,...,Computer Science,S4WT3,NaN,hybrid,NaN,NaN,2025-03-10,WOS:000970223600001,0,q3
75,C,"Stickley, D",NaN,NaN,ASSOC COMPUTAT LINGUIST,"Stickley, Daniel",NaN,NaN,Relating Relations: Meta-Relation Extraction f...,EACL 2021: THE 16TH CONFERENCE OF THE EUROPEAN...,...,Computer Science; Linguistics,BT9HU,NaN,NaN,NaN,NaN,2025-03-10,WOS:000861067300018,0,q3
76,J,"Gao, F; Song, XR; Gu, JG; Zhang, LH; Liu, Y; Z...",NaN,NaN,NaN,"Gao, Feng; Song, Xuren; Gu, Jinguang; Zhang, L...",NaN,NaN,Fine-Grained Relation Extraction for Drug Inst...,IEEE ACCESS,...,Computer Science; Engineering; Telecommunications,I8YS2,NaN,gold,NaN,NaN,2025-03-10,WOS:001005589400001,0,q3
77,C,"Zheng, YD; Anran, H; Tuan, LA",NaN,"Rogers, A; Boyd-Graber, J; Okazaki, N",NaN,"Zheng Yandan; Anran, Hao; Tuan, Luu Anh",NaN,NaN,Jointprop: Joint Semi-supervised Learning for ...,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,...,Computer Science,BW7IT,NaN,NaN,NaN,NaN,2025-03-10,WOS:001190962506018,0,q3
78,J,"Tong, YT; Tong, JJ; Xia, SD; Zhou, QL; Shen, YQ",NaN,NaN,NaN,"Tong, Yetao; Tong, Jijun; Xia, Shudong; Zhou, ...",NaN,NaN,CECRel: A joint entity and relation extraction...,JOURNAL OF BIOMEDICAL INFORMATICS,...,Computer Science; Medical Informatics,Y9G8X,40010480.0,NaN,NaN,NaN,2025-03-10,WOS:001435127300001,0,q3