# Paper selection
The data we use is filter by queries by default in other two notebooks instead of removing folders.

In [1]:
import pandas as pd

In [ ]:
# Scopus
scopus = pd.read_csv("./scopus/scopus_reducido.csv")

In [3]:
scopus['search_engine'] = 'Scopus'

scopus.columns = scopus.columns.str.lower()
print(len(scopus.columns))
scopus.columns

49

Index(['unnamed: 0', 'authors', 'author full names', 'author(s) id', 'title',
       'year', 'source title', 'volume', 'issue', 'art. no.', 'page start',
       'page end', 'page count', 'cited by', 'doi', 'link', 'affiliations',
       'authors with affiliations', 'abstract', 'author keywords',
       'index keywords', 'molecular sequence numbers', 'chemicals/cas',
       'tradenames', 'manufacturers', 'funding details', 'funding texts',
       'references', 'correspondence address', 'editors', 'publisher',
       'sponsors', 'conference name', 'conference date', 'conference location',
       'conference code', 'issn', 'isbn', 'coden', 'pubmed id',
       'language of original document', 'abbreviated source title',
       'document type', 'publication stage', 'open access', 'source', 'eid',
       'query', 'search_engine'],
      dtype='object')

In [ ]:
# Wos
wos = pd.read_csv("./web_of_science/wos_reducido.csv")

In [5]:
wos['search_engine'] = 'Web of Science'

wos.columns = wos.columns.str.lower()
print(len(wos.columns))
wos.columns

75

Index(['unnamed: 0', 'publication type', 'authors', 'book authors',
       'book editors', 'book group authors', 'author full names',
       'book author full names', 'group authors', 'article title',
       'source title', 'book series title', 'book series subtitle', 'language',
       'document type', 'conference title', 'conference date',
       'conference location', 'conference sponsor', 'conference host',
       'author keywords', 'keywords plus', 'abstract', 'addresses',
       'affiliations', 'reprint addresses', 'email addresses',
       'researcher ids', 'orcids', 'funding orgs', 'funding name preferred',
       'funding text', 'cited references', 'cited reference count',
       'times cited, wos core', 'times cited, all databases',
       '180 day usage count', 'since 2013 usage count', 'publisher',
       'publisher city', 'publisher address', 'issn', 'eissn', 'isbn',
       'journal abbreviation', 'journal iso abbreviation', 'publication date',
       'publication year', 'volume', 'issue', 'part number', 'supplement',
       'special issue', 'meeting abstract', 'start page', 'end page',
       'article number', 'doi', 'doi link', 'book doi', 'early access date',
       'number of pages', 'wos categories', 'web of science index',
       'research areas', 'ids number', 'pubmed id', 'open access designations',
       'highly cited status', 'hot paper status', 'date of export',
       'ut (unique wos id)', 'web of science record', 'query',
       'search_engine'],
      dtype='object')

In [6]:
# 2. Obtener los conjuntos de nombres de columnas de cada DataFrame
cols_df1 = set(scopus.columns)
cols_df2 = set(wos.columns)

# 3. Identificar columnas comunes y diferencias
columnas_comunes = cols_df1.intersection(cols_df2)
columnas_solo_df1 = cols_df1 - cols_df2
columnas_solo_df2 = cols_df2 - cols_df1

# Mostrar resultados
print("Columnas comunes:", columnas_comunes)
print("Columnas solo en df1:", columnas_solo_df1)
print("Columnas solo en df2:", columnas_solo_df2)

Columnas comunes: {'author full names', 'document type', 'issn', 'isbn', 'conference date', 'conference location', 'affiliations', 'author keywords', 'query', 'publisher', 'unnamed: 0', 'pubmed id', 'search_engine', 'source title', 'abstract', 'issue', 'doi', 'authors', 'volume'}
Columnas solo en df1: {'page start', 'language of original document', 'year', 'author(s) id', 'page count', 'correspondence address', 'funding texts', 'editors', 'publication stage', 'funding details', 'art. no.', 'conference name', 'cited by', 'link', 'chemicals/cas', 'open access', 'eid', 'page end', 'molecular sequence numbers', 'abbreviated source title', 'coden', 'manufacturers', 'title', 'conference code', 'tradenames', 'source', 'sponsors', 'references', 'index keywords', 'authors with affiliations'}
Columnas solo en df2: {'publication type', 'book group authors', 'language', 'special issue', 'article number', 'publication date', 'reprint addresses', 'orcids', 'funding text', 'times cited, wos core', 'keywords plus', 'supplement', 'book editors', 'start page', 'ut (unique wos id)', 'early access date', 'open access designations', 'web of science record', 'book author full names', 'publisher address', 'since 2013 usage count', 'journal abbreviation', 'journal iso abbreviation', 'book doi', 'book series subtitle', 'researcher ids', 'eissn', 'cited reference count', 'part number', 'publisher city', 'conference host', 'publication year', 'meeting abstract', 'research areas', 'conference title', 'times cited, all databases', 'book series title', 'funding orgs', '180 day usage count', 'number of pages', 'ids number', 'article title', 'email addresses', 'highly cited status', 'web of science index', 'date of export', 'group authors', 'funding name preferred', 'cited references', 'hot paper status', 'doi link', 'end page', 'book authors', 'wos categories', 'conference sponsor', 'addresses'}

In [7]:
# import pandas as pd

# # Supongamos que ya tienes cargados df1 y df2

# # Diccionario de renombrado para df2: 
# # Se toma el nombre de df1 como referencia para unificar los nombres.
# rename_dict_df2 = {
#     # "doi link": "doi",
#     "book doi": "doi",
#     "article title": "title",
#     "start page": "page start",
#     "end page": "page end",
#     "number of pages": "page count",
#     "publication year": "year",
#     "times cited, all databases": "cited by",
#     "article number": "art. no.",
#     "researcher ids": "author(s) id",
#     "ut (unique wos id)": "eid",
#     "open access designations": "open access"
# }

# # Renombramos las columnas de df2
# df2_renamed = wos.rename(columns=rename_dict_df2)
# display(df2_renamed)

# # Función para combinar columnas duplicadas resultantes del renombrado
# def combine_duplicate_columns(df):
#     # Para cada columna que aparezca más de una vez
#     for col in set(df.columns):
#         if list(df.columns).count(col) > 1:
#             # Combina las columnas duplicadas: se toma el primer valor no nulo en cada fila
#             df[col] = df.loc[:, df.columns == col].bfill(axis=1).iloc[:, 0]
#             # Luego se eliminan las columnas duplicadas, conservando la primera
#             df = df.loc[:, ~df.columns.duplicated(keep='first')]
#     return df

# df2_renamed = combine_duplicate_columns(df2_renamed)
# display(df2_renamed)

In [8]:
import pandas as pd

# Supongamos que ya tienes cargados tus DataFrames: df1 y df2

# Convertir los nombres de las columnas a minúsculas en ambos DataFrames
scopus.columns = scopus.columns.str.lower()
wos.columns = wos.columns.str.lower()

# Definir un diccionario para renombrar columnas de df2 usando df1 como referencia.
# Se mapea cada nombre de df2 al nombre equivalente en df1.
rename_dict_df2 = {
    # Título del artículo
    "article title": "title",
    
    # Páginas: df1 tiene "page start" y "page end"
    "start page": "page start",
    "end page": "page end",
    
    # Referencias citadas
    "cited references": "references",
    
    # Año de publicación
    "publication year": "year",
    
    # Idioma
    "language": "language of original document",
    
    # Abreviatura del título de la fuente
    "journal iso abbreviation": "abbreviated source title",
    # (Si en df2 aparece "journal abbreviation", podrías mapearlo de igual forma)
    
    # Número de artículo
    "article number": "art. no.",
    
    # Financiamiento (se consolidan en una única columna de referencia)
    # "funding orgs": "funding details",
    # "funding text": "funding details",
    "funding name preferred": "funding details",
    
    # Identificadores de autor
    "researcher ids": "author(s) id",
    "orcids": "author(s) id",
    
    # Enlace o URL del artículo
    "doi link": "link",
    
    # Citaciones
    "times cited, all databases": "cited by",
    # "times cited, wos core": "cited by",
    
    # Nombre de la conferencia
    "conference title": "conference name"
}

# Renombramos las columnas de df2
df2_renamed = wos.rename(columns=rename_dict_df2)
# display(df2_renamed)

# Función para combinar columnas duplicadas resultantes del renombrado
def combine_duplicate_columns(df):
    # Para cada columna que aparezca más de una vez
    for col in set(df.columns):
        if list(df.columns).count(col) > 1:
            # Combina las columnas duplicadas: se toma el primer valor no nulo en cada fila
            df[col] = df.loc[:, df.columns == col].bfill(axis=1).iloc[:, 0]
            # Luego se eliminan las columnas duplicadas, conservando la primera
            df = df.loc[:, ~df.columns.duplicated(keep='first')]
    return df

df2_renamed = combine_duplicate_columns(df2_renamed)
display(df2_renamed)

,unnamed: 0,publication type,authors,book authors,book editors,book group authors,author full names,book author full names,group authors,title,...,ids number,pubmed id,open access designations,highly cited status,hot paper status,date of export,ut (unique wos id),web of science record,query,search_engine
0,0,C,"Zhou, WX; Zhang, S; Naumann, T; Chen, MH; Poon, H",NaN,"Rogers, A; Boyd-Graber, J; Okazaki, N",NaN,"Zhou, Wenxuan; Zhang, Sheng; Naumann, Tristan;...",NaN,NaN,Continual Contrastive Finetuning Improves Low-...,...,BW7IT,NaN,NaN,NaN,NaN,2025-03-10,WOS:001190962505001,0,q1,Web of Science
1,1,C,"Hu, XM; Zhang, CW; Yang, YW; Li, XH; Lin, L; W...",NaN,NaN,Assoc Computat Linguist,"Hu, Xuming; Zhang, Chenwei; Yang, Yawen; Li, X...",NaN,NaN,Gradient Imitation Reinforcement Learning for ...,...,BT8XM,NaN,NaN,NaN,NaN,2025-03-10,WOS:000855966302075,0,q1,Web of Science
2,2,J,"Wu, XP; Hu, J; Wan, WJ; Zhang, BX; Li, CJ",NaN,NaN,NaN,"Wu, Xiangping; Hu, Jun; Wan, Wangjun; Zhang, B...",NaN,NaN,Incentive Instruction for Event Relation Extra...,...,WQ0O6,NaN,gold,NaN,NaN,2025-03-10,WOS:001256223200001,0,q1,Web of Science
3,3,J,"Guo, Q; Guo, Y; Zhao, J",NaN,NaN,NaN,"Guo, Qian; Guo, Yi; Zhao, Jin",NaN,NaN,HRCL: Hierarchical Relation Contrastive Learni...,...,PL6F5,38683710.0,NaN,NaN,NaN,2025-03-10,WOS:001214266300001,0,q1,Web of Science
4,4,C,"Yu, JJ; Wang, X; Chen, WL",NaN,"Wooldridge, M; Dy, J; Natarajan, S",NaN,"Yu, Junjie; Wang, Xing; Chen, Wenliang",NaN,NaN,Reliable Data Generation and Selection for Low...,...,BX0WL,NaN,NaN,NaN,NaN,2025-03-10,WOS:001239407300105,0,q1,Web of Science
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,74,J,"Moscato, V; Napolano, G; Postiglione, M; Sperl...",NaN,NaN,NaN,"Moscato, Vincenzo; Napolano, Giuseppe; Postigl...",NaN,NaN,Multi-task learning for few-shot biomedical re...,...,S4WT3,NaN,hybrid,NaN,NaN,2025-03-10,WOS:000970223600001,0,q3,Web of Science
58,75,C,"Stickley, D",NaN,NaN,ASSOC COMPUTAT LINGUIST,"Stickley, Daniel",NaN,NaN,Relating Relations: Meta-Relation Extraction f...,...,BT9HU,NaN,NaN,NaN,NaN,2025-03-10,WOS:000861067300018,0,q3,Web of Science
59,76,J,"Gao, F; Song, XR; Gu, JG; Zhang, LH; Liu, Y; Z...",NaN,NaN,NaN,"Gao, Feng; Song, Xuren; Gu, Jinguang; Zhang, L...",NaN,NaN,Fine-Grained Relation Extraction for Drug Inst...,...,I8YS2,NaN,gold,NaN,NaN,2025-03-10,WOS:001005589400001,0,q3,Web of Science
60,77,C,"Zheng, YD; Anran, H; Tuan, LA",NaN,"Rogers, A; Boyd-Graber, J; Okazaki, N",NaN,"Zheng Yandan; Anran, Hao; Tuan, Luu Anh",NaN,NaN,Jointprop: Joint Semi-supervised Learning for ...,...,BW7IT,NaN,NaN,NaN,NaN,2025-03-10,WOS:001190962506018,0,q3,Web of Science
61,78,J,"Tong, YT; Tong, JJ; Xia, SD; Zhou, QL; Shen, YQ",NaN,NaN,NaN,"Tong, Yetao; Tong, Jijun; Xia, Shudong; Zhou, ...",NaN,NaN,CECRel: A joint entity and relation extraction...,...,Y9G8X,40010480.0,NaN,NaN,NaN,2025-03-10,WOS:001435127300001,0,q3,Web of Science

In [9]:
import pandas as pd

# Supongamos que ya tienes df1 y df2

# Reindexamos df2 para que tenga únicamente las columnas de df1 (en el mismo orden)
df2_aligned = wos.reindex(columns=scopus.columns)
display(df2_aligned)

,unnamed: 0,authors,author full names,author(s) id,title,year,source title,volume,issue,art. no.,...,pubmed id,language of original document,abbreviated source title,document type,publication stage,open access,source,eid,query,search_engine
0,0,"Zhou, WX; Zhang, S; Naumann, T; Chen, MH; Poon, H","Zhou, Wenxuan; Zhang, Sheng; Naumann, Tristan;...",NaN,NaN,NaN,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q1,Web of Science
1,1,"Hu, XM; Zhang, CW; Yang, YW; Li, XH; Lin, L; W...","Hu, Xuming; Zhang, Chenwei; Yang, Yawen; Li, X...",NaN,NaN,NaN,2021 CONFERENCE ON EMPIRICAL METHODS IN NATURA...,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q1,Web of Science
2,2,"Wu, XP; Hu, J; Wan, WJ; Zhang, BX; Li, CJ","Wu, Xiangping; Hu, Jun; Wan, Wangjun; Zhang, B...",NaN,NaN,NaN,IEEE ACCESS,12.0,NaN,NaN,...,NaN,NaN,NaN,Article,NaN,NaN,NaN,NaN,q1,Web of Science
3,3,"Guo, Q; Guo, Y; Zhao, J","Guo, Qian; Guo, Yi; Zhao, Jin",NaN,NaN,NaN,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,NaN,NaN,NaN,...,38683710.0,NaN,NaN,Article; Early Access,NaN,NaN,NaN,NaN,q1,Web of Science
4,4,"Yu, JJ; Wang, X; Chen, WL","Yu, Junjie; Wang, Xing; Chen, Wenliang",NaN,NaN,NaN,THIRTY-EIGHTH AAAI CONFERENCE ON ARTIFICIAL IN...,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q1,Web of Science
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,74,"Moscato, V; Napolano, G; Postiglione, M; Sperl...","Moscato, Vincenzo; Napolano, Giuseppe; Postigl...",NaN,NaN,NaN,ARTIFICIAL INTELLIGENCE REVIEW,56.0,11.0,NaN,...,NaN,NaN,NaN,Article,NaN,NaN,NaN,NaN,q3,Web of Science
58,75,"Stickley, D","Stickley, Daniel",NaN,NaN,NaN,EACL 2021: THE 16TH CONFERENCE OF THE EUROPEAN...,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q3,Web of Science
59,76,"Gao, F; Song, XR; Gu, JG; Zhang, LH; Liu, Y; Z...","Gao, Feng; Song, Xuren; Gu, Jinguang; Zhang, L...",NaN,NaN,NaN,IEEE ACCESS,11.0,NaN,NaN,...,NaN,NaN,NaN,Article,NaN,NaN,NaN,NaN,q3,Web of Science
60,77,"Zheng, YD; Anran, H; Tuan, LA","Zheng Yandan; Anran, Hao; Tuan, Luu Anh",NaN,NaN,NaN,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q3,Web of Science
61,78,"Tong, YT; Tong, JJ; Xia, SD; Zhou, QL; Shen, YQ","Tong, Yetao; Tong, Jijun; Xia, Shudong; Zhou, ...",NaN,NaN,NaN,JOURNAL OF BIOMEDICAL INFORMATICS,164.0,NaN,NaN,...,40010480.0,NaN,NaN,Article,NaN,NaN,NaN,NaN,q3,Web of Science

In [10]:
# import re

# titulos_final = scopus["title"].tolist()
# print(len(titulos_final))
# titulos_wos = df2_aligned["title"].tolist() # wos
# print(len(titulos_wos))

# def normalize_title(t):
#     if isinstance(t, str):
#         t = t.strip().lower()
#         # Eliminar signos de puntuación
#         t = re.sub(r'[^\w\s]', '', t)
#         # Reducir espacios múltiples a uno solo
#         t = re.sub(r'\s+', ' ', t)
#         return t
#     return ''

# # Normalizar ambas listas
# titulos_final_clean = [normalize_title(t) for t in titulos_final]
# titulos_wos_clean = [normalize_title(t) for t in titulos_wos]

# # Calcular la intersección
# common_titles = set(titulos_final_clean).intersection(set(titulos_wos_clean))
# print("Número de títulos comunes:", len(common_titles))

In [11]:


# Concatenamos ambos DataFrames (se alinearán por nombre de columna)
df_total = pd.concat([scopus, df2_aligned], ignore_index=True)
df_total = df_total.drop("unnamed: 0", axis=1)

display(df_total)

,authors,author full names,author(s) id,title,year,source title,volume,issue,art. no.,page start,...,pubmed id,language of original document,abbreviated source title,document type,publication stage,open access,source,eid,query,search_engine
0,Zhong J.; Liu Y.; Ouyang C.; Ren L.; Zhu C.; H...,"Zhong, Jin (59423140700); Liu, Yongbin (564967...",59423140700; 56496782000; 35226676500; 5826517...,CouBRE: Counterfactual NLI For Low-Resource Bi...,2025.0,Lecture Notes in Computer Science (including s...,15360 LNAI,NaN,NaN,109.0,...,NaN,English,Lect. Notes Comput. Sci.,Conference paper,Final,NaN,Scopus,2-s2.0-85210083717,q1,Scopus
1,Xu X.; Chen X.; Zhang N.; Xie X.; Chen X.; Che...,"Xu, Xin (57421213500); Chen, Xiang (5915764150...",57421213500; 59157641500; 55923601900; 5722237...,Towards Realistic Low-resource Relation Extrac...,2022.0,Findings of the Association for Computational ...,NaN,NaN,NaN,413.0,...,NaN,English,Find. Assoc. Comput. Linguist.: EMNLP,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85149872682,q1,Scopus
2,Dong M.; Pan C.; Luo Z.,"Dong, Manqing (57202994996); Pan, Chunguang (5...",57202994996; 57223040498; 57210633943,MapRE: An Effective Semantic Mapping Approach ...,2021.0,EMNLP 2021 - 2021 Conference on Empirical Meth...,NaN,NaN,NaN,2694.0,...,NaN,English,EMNLP - Conf. Empir. Methods Nat. Lang. Proces...,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85127414858,q1,Scopus
3,Yu J.; Wang X.; Chen W.,"Yu, Junjie (57189380183); Wang, Xing (55978420...",57189380183; 55978420400; 55715988100,Reliable Data Generation and Selection for Low...,2024.0,Proceedings of the AAAI Conference on Artifici...,38,17.0,NaN,19440.0,...,NaN,English,Proc. AAAI Conf. Artif. Intell.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85189627963,q1,Scopus
4,Wang P.; Shao T.; Ji K.; Li G.; Ke W.,"Wang, Peng (56182131700); Shao, Tong (57340534...",56182131700; 57340534200; 58339210600; 5734716...,fmLRE: A Low-Resource Relation Extraction Mode...,2023.0,Proceedings of the 37th AAAI Conference on Art...,37,NaN,NaN,13700.0,...,NaN,English,"Proc. AAAI Conf. Artif. Intell., AAAI",Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85167973559,q1,Scopus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,"Moscato, V; Napolano, G; Postiglione, M; Sperl...","Moscato, Vincenzo; Napolano, Giuseppe; Postigl...",NaN,NaN,NaN,ARTIFICIAL INTELLIGENCE REVIEW,56.0,11.0,NaN,NaN,...,NaN,NaN,NaN,Article,NaN,NaN,NaN,NaN,q3,Web of Science
222,"Stickley, D","Stickley, Daniel",NaN,NaN,NaN,EACL 2021: THE 16TH CONFERENCE OF THE EUROPEAN...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q3,Web of Science
223,"Gao, F; Song, XR; Gu, JG; Zhang, LH; Liu, Y; Z...","Gao, Feng; Song, Xuren; Gu, Jinguang; Zhang, L...",NaN,NaN,NaN,IEEE ACCESS,11.0,NaN,NaN,NaN,...,NaN,NaN,NaN,Article,NaN,NaN,NaN,NaN,q3,Web of Science
224,"Zheng, YD; Anran, H; Tuan, LA","Zheng Yandan; Anran, Hao; Tuan, Luu Anh",NaN,NaN,NaN,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q3,Web of Science
225,"Tong, YT; Tong, JJ; Xia, SD; Zhou, QL; Shen, YQ","Tong, Yetao; Tong, Jijun; Xia, Shudong; Zhou, ...",NaN,NaN,NaN,JOURNAL OF BIOMEDICAL INFORMATICS,164.0,NaN,NaN,NaN,...,40010480.0,NaN,NaN,Article,NaN,NaN,NaN,NaN,q3,Web of Science

In [12]:
# # Realizamos el concat: las columnas con el mismo nombre se alinean, evitando duplicados
# df_total = pd.concat([scopus, df2_renamed], ignore_index=True, sort=False)

# # Mostramos las primeras filas del DataFrame resultante
# display(df_total)

In [13]:
df_total.columns

Index(['authors', 'author full names', 'author(s) id', 'title', 'year',
       'source title', 'volume', 'issue', 'art. no.', 'page start', 'page end',
       'page count', 'cited by', 'doi', 'link', 'affiliations',
       'authors with affiliations', 'abstract', 'author keywords',
       'index keywords', 'molecular sequence numbers', 'chemicals/cas',
       'tradenames', 'manufacturers', 'funding details', 'funding texts',
       'references', 'correspondence address', 'editors', 'publisher',
       'sponsors', 'conference name', 'conference date', 'conference location',
       'conference code', 'issn', 'isbn', 'coden', 'pubmed id',
       'language of original document', 'abbreviated source title',
       'document type', 'publication stage', 'open access', 'source', 'eid',
       'query', 'search_engine'],
      dtype='object')

In [14]:
import pandas as pd

# Suponiendo que tu DataFrame se llama df
conteo = df_total['search_engine'].value_counts()
print(conteo)

search_engine
Scopus            164
Web of Science     62
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Supón que ya tienes el DataFrame 'df'
initial_rows = df_total.shape[0]  # Número de filas inicial

# Eliminar filas duplicadas (puedes usar inplace=True para modificar el mismo DataFrame)
df_total_final = df_total.drop_duplicates(subset='title', keep='first')
# df_total_final = df_total.drop_duplicates()

final_rows = df_total_final.shape[0]  # Número de filas después de eliminar duplicados

filas_eliminadas = initial_rows - final_rows

print(f"Se han eliminado {filas_eliminadas} filas duplicadas.")
df_total_final.to_csv("summary.csv", encoding="utf-8")

Se han eliminado 61 filas duplicadas.

In [16]:
# # Agrupar por título y contar los motores de búsqueda únicos para cada título
# source_counts = df_total.groupby('title')['search_engine'].nunique()

# # Extraer los títulos que aparecen en más de un motor de búsqueda
# both_titles = source_counts[source_counts > 1].index

# # Actualizar la columna "search engine" en df_total_final a "Both" para los títulos identificados
# df_total_final.loc[df_total_final['title'].isin(both_titles), 'search_engine'] = 'Both'

In [17]:
display(df_total_final)

,authors,author full names,author(s) id,title,year,source title,volume,issue,art. no.,page start,...,pubmed id,language of original document,abbreviated source title,document type,publication stage,open access,source,eid,query,search_engine
0,Zhong J.; Liu Y.; Ouyang C.; Ren L.; Zhu C.; H...,"Zhong, Jin (59423140700); Liu, Yongbin (564967...",59423140700; 56496782000; 35226676500; 5826517...,CouBRE: Counterfactual NLI For Low-Resource Bi...,2025.0,Lecture Notes in Computer Science (including s...,15360 LNAI,NaN,NaN,109.0,...,NaN,English,Lect. Notes Comput. Sci.,Conference paper,Final,NaN,Scopus,2-s2.0-85210083717,q1,Scopus
1,Xu X.; Chen X.; Zhang N.; Xie X.; Chen X.; Che...,"Xu, Xin (57421213500); Chen, Xiang (5915764150...",57421213500; 59157641500; 55923601900; 5722237...,Towards Realistic Low-resource Relation Extrac...,2022.0,Findings of the Association for Computational ...,NaN,NaN,NaN,413.0,...,NaN,English,Find. Assoc. Comput. Linguist.: EMNLP,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85149872682,q1,Scopus
2,Dong M.; Pan C.; Luo Z.,"Dong, Manqing (57202994996); Pan, Chunguang (5...",57202994996; 57223040498; 57210633943,MapRE: An Effective Semantic Mapping Approach ...,2021.0,EMNLP 2021 - 2021 Conference on Empirical Meth...,NaN,NaN,NaN,2694.0,...,NaN,English,EMNLP - Conf. Empir. Methods Nat. Lang. Proces...,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85127414858,q1,Scopus
3,Yu J.; Wang X.; Chen W.,"Yu, Junjie (57189380183); Wang, Xing (55978420...",57189380183; 55978420400; 55715988100,Reliable Data Generation and Selection for Low...,2024.0,Proceedings of the AAAI Conference on Artifici...,38,17.0,NaN,19440.0,...,NaN,English,Proc. AAAI Conf. Artif. Intell.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85189627963,q1,Scopus
4,Wang P.; Shao T.; Ji K.; Li G.; Ke W.,"Wang, Peng (56182131700); Shao, Tong (57340534...",56182131700; 57340534200; 58339210600; 5734716...,fmLRE: A Low-Resource Relation Extraction Mode...,2023.0,Proceedings of the 37th AAAI Conference on Art...,37,NaN,NaN,13700.0,...,NaN,English,"Proc. AAAI Conf. Artif. Intell., AAAI",Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85167973559,q1,Scopus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,Sachan M.; Dubey A.; Mitchell T.; Roth D.; Xin...,"Sachan, Mrinmaya (36094978300); Dubey, Avinava...",36094978300; 36016208000; 7402175019; 74016690...,Learning pipelines with limited data and domai...,2018.0,Advances in Neural Information Processing Systems,2018-December,NaN,NaN,140.0,...,NaN,English,Adv. neural inf. proces. syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85064808357,q3,Scopus
161,Stickley D.,"Stickley, Daniel (57224354310)",57224354310,Relating relations: Meta-relation extraction f...,2021.0,EACL 2021 - 16th Conference of the European Ch...,NaN,NaN,NaN,129.0,...,NaN,English,EACL - Conf. Eur. Chapter Assoc. Comput. Lingu...,Conference paper,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85107459083,q3,Scopus
162,Yang X.; Mao K.; Zhao R.,"Yang, Xuefeng (56194089500); Mao, Kezhi (70064...",56194089500; 7006403609; 56717092800,Distributional sentence representation by expe...,2016.0,2015 10th International Conference on Informat...,NaN,NaN,7459848,NaN,...,NaN,English,"Int. Conf. Inf., Commun. Signal Process., ICICS",Conference paper,Final,NaN,Scopus,2-s2.0-84973636068,q3,Scopus
163,Bhatnagar R.; Sardar S.; Beheshti M.; Podichet...,"Bhatnagar, Roopal (57390567800); Sardar, Saksh...",57390567800; 57208109642; 35752962700; 5521654...,How can natural language processing help model...,2022.0,JAMIA Open,5,2.0,ooac043,NaN,...,NaN,English,JAMIA Open,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85134911178,q3,Scopus
164,"Zhou, WX; Zhang, S; Naumann, T; Chen, MH; Poon, H","Zhou, Wenxuan; Zhang, Sheng; Naumann, Tristan;...",NaN,NaN,NaN,PROCEEDINGS OF THE 61ST ANNUAL MEETING OF THE ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Proceedings Paper,NaN,NaN,NaN,NaN,q1,Web of Science

In [18]:
import pandas as pd

# Suponiendo que tu DataFrame se llama df
conteo = df_total_final['search_engine'].value_counts()
print(conteo)

search_engine
Scopus            164
Web of Science      1
Name: count, dtype: int64

# Inclusion / exclusion

## 1. Written in english

In [19]:
# 1. Written in english	
final = df_total_final[df_total_final["language of original document"] == "English"]
display(final)

,authors,author full names,author(s) id,title,year,source title,volume,issue,art. no.,page start,...,pubmed id,language of original document,abbreviated source title,document type,publication stage,open access,source,eid,query,search_engine
0,Zhong J.; Liu Y.; Ouyang C.; Ren L.; Zhu C.; H...,"Zhong, Jin (59423140700); Liu, Yongbin (564967...",59423140700; 56496782000; 35226676500; 5826517...,CouBRE: Counterfactual NLI For Low-Resource Bi...,2025.0,Lecture Notes in Computer Science (including s...,15360 LNAI,NaN,NaN,109.0,...,NaN,English,Lect. Notes Comput. Sci.,Conference paper,Final,NaN,Scopus,2-s2.0-85210083717,q1,Scopus
1,Xu X.; Chen X.; Zhang N.; Xie X.; Chen X.; Che...,"Xu, Xin (57421213500); Chen, Xiang (5915764150...",57421213500; 59157641500; 55923601900; 5722237...,Towards Realistic Low-resource Relation Extrac...,2022.0,Findings of the Association for Computational ...,NaN,NaN,NaN,413.0,...,NaN,English,Find. Assoc. Comput. Linguist.: EMNLP,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85149872682,q1,Scopus
2,Dong M.; Pan C.; Luo Z.,"Dong, Manqing (57202994996); Pan, Chunguang (5...",57202994996; 57223040498; 57210633943,MapRE: An Effective Semantic Mapping Approach ...,2021.0,EMNLP 2021 - 2021 Conference on Empirical Meth...,NaN,NaN,NaN,2694.0,...,NaN,English,EMNLP - Conf. Empir. Methods Nat. Lang. Proces...,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85127414858,q1,Scopus
3,Yu J.; Wang X.; Chen W.,"Yu, Junjie (57189380183); Wang, Xing (55978420...",57189380183; 55978420400; 55715988100,Reliable Data Generation and Selection for Low...,2024.0,Proceedings of the AAAI Conference on Artifici...,38,17.0,NaN,19440.0,...,NaN,English,Proc. AAAI Conf. Artif. Intell.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85189627963,q1,Scopus
4,Wang P.; Shao T.; Ji K.; Li G.; Ke W.,"Wang, Peng (56182131700); Shao, Tong (57340534...",56182131700; 57340534200; 58339210600; 5734716...,fmLRE: A Low-Resource Relation Extraction Mode...,2023.0,Proceedings of the 37th AAAI Conference on Art...,37,NaN,NaN,13700.0,...,NaN,English,"Proc. AAAI Conf. Artif. Intell., AAAI",Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85167973559,q1,Scopus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Gao F.; Song X.; Gu J.; Zhang L.; Liu Y.; Zhan...,"Gao, Feng (50061267800); Song, Xuren (58303593...",50061267800; 58303593500; 8311080000; 57249181...,Fine-Grained Relation Extraction for Drug Inst...,2023.0,IEEE Access,11,NaN,NaN,51777.0,...,NaN,English,IEEE Access,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85160999982,q3,Scopus
160,Sachan M.; Dubey A.; Mitchell T.; Roth D.; Xin...,"Sachan, Mrinmaya (36094978300); Dubey, Avinava...",36094978300; 36016208000; 7402175019; 74016690...,Learning pipelines with limited data and domai...,2018.0,Advances in Neural Information Processing Systems,2018-December,NaN,NaN,140.0,...,NaN,English,Adv. neural inf. proces. syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85064808357,q3,Scopus
161,Stickley D.,"Stickley, Daniel (57224354310)",57224354310,Relating relations: Meta-relation extraction f...,2021.0,EACL 2021 - 16th Conference of the European Ch...,NaN,NaN,NaN,129.0,...,NaN,English,EACL - Conf. Eur. Chapter Assoc. Comput. Lingu...,Conference paper,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85107459083,q3,Scopus
162,Yang X.; Mao K.; Zhao R.,"Yang, Xuefeng (56194089500); Mao, Kezhi (70064...",56194089500; 7006403609; 56717092800,Distributional sentence representation by expe...,2016.0,2015 10th International Conference on Informat...,NaN,NaN,7459848,NaN,...,NaN,English,"Int. Conf. Inf., Commun. Signal Process., ICICS",Conference paper,Final,NaN,Scopus,2-s2.0-84973636068,q3,Scopus
163,Bhatnagar R.; Sardar S.; Beheshti M.; Podichet...,"Bhatnagar, Roopal (57390567800); Sardar, Saksh...",57390567800; 57208109642; 35752962700; 5521654...,How can natural language processing help model...,2022.0,JAMIA Open,5,2.0,ooac043,NaN,...,NaN,English,JAMIA Open,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85134911178,q3,Scopus

## 2. Remove proceedings
Proceedings put noisy in the metadata excel due to they group papers that are already in the mentioned excel.

In [20]:
# 2. Remove proceedings
final = final.dropna(subset=["authors", "author full names", "author(s) id"])
display(final)

,authors,author full names,author(s) id,title,year,source title,volume,issue,art. no.,page start,...,pubmed id,language of original document,abbreviated source title,document type,publication stage,open access,source,eid,query,search_engine
0,Zhong J.; Liu Y.; Ouyang C.; Ren L.; Zhu C.; H...,"Zhong, Jin (59423140700); Liu, Yongbin (564967...",59423140700; 56496782000; 35226676500; 5826517...,CouBRE: Counterfactual NLI For Low-Resource Bi...,2025.0,Lecture Notes in Computer Science (including s...,15360 LNAI,NaN,NaN,109.0,...,NaN,English,Lect. Notes Comput. Sci.,Conference paper,Final,NaN,Scopus,2-s2.0-85210083717,q1,Scopus
1,Xu X.; Chen X.; Zhang N.; Xie X.; Chen X.; Che...,"Xu, Xin (57421213500); Chen, Xiang (5915764150...",57421213500; 59157641500; 55923601900; 5722237...,Towards Realistic Low-resource Relation Extrac...,2022.0,Findings of the Association for Computational ...,NaN,NaN,NaN,413.0,...,NaN,English,Find. Assoc. Comput. Linguist.: EMNLP,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85149872682,q1,Scopus
2,Dong M.; Pan C.; Luo Z.,"Dong, Manqing (57202994996); Pan, Chunguang (5...",57202994996; 57223040498; 57210633943,MapRE: An Effective Semantic Mapping Approach ...,2021.0,EMNLP 2021 - 2021 Conference on Empirical Meth...,NaN,NaN,NaN,2694.0,...,NaN,English,EMNLP - Conf. Empir. Methods Nat. Lang. Proces...,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85127414858,q1,Scopus
3,Yu J.; Wang X.; Chen W.,"Yu, Junjie (57189380183); Wang, Xing (55978420...",57189380183; 55978420400; 55715988100,Reliable Data Generation and Selection for Low...,2024.0,Proceedings of the AAAI Conference on Artifici...,38,17.0,NaN,19440.0,...,NaN,English,Proc. AAAI Conf. Artif. Intell.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85189627963,q1,Scopus
4,Wang P.; Shao T.; Ji K.; Li G.; Ke W.,"Wang, Peng (56182131700); Shao, Tong (57340534...",56182131700; 57340534200; 58339210600; 5734716...,fmLRE: A Low-Resource Relation Extraction Mode...,2023.0,Proceedings of the 37th AAAI Conference on Art...,37,NaN,NaN,13700.0,...,NaN,English,"Proc. AAAI Conf. Artif. Intell., AAAI",Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85167973559,q1,Scopus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Gao F.; Song X.; Gu J.; Zhang L.; Liu Y.; Zhan...,"Gao, Feng (50061267800); Song, Xuren (58303593...",50061267800; 58303593500; 8311080000; 57249181...,Fine-Grained Relation Extraction for Drug Inst...,2023.0,IEEE Access,11,NaN,NaN,51777.0,...,NaN,English,IEEE Access,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85160999982,q3,Scopus
160,Sachan M.; Dubey A.; Mitchell T.; Roth D.; Xin...,"Sachan, Mrinmaya (36094978300); Dubey, Avinava...",36094978300; 36016208000; 7402175019; 74016690...,Learning pipelines with limited data and domai...,2018.0,Advances in Neural Information Processing Systems,2018-December,NaN,NaN,140.0,...,NaN,English,Adv. neural inf. proces. syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85064808357,q3,Scopus
161,Stickley D.,"Stickley, Daniel (57224354310)",57224354310,Relating relations: Meta-relation extraction f...,2021.0,EACL 2021 - 16th Conference of the European Ch...,NaN,NaN,NaN,129.0,...,NaN,English,EACL - Conf. Eur. Chapter Assoc. Comput. Lingu...,Conference paper,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85107459083,q3,Scopus
162,Yang X.; Mao K.; Zhao R.,"Yang, Xuefeng (56194089500); Mao, Kezhi (70064...",56194089500; 7006403609; 56717092800,Distributional sentence representation by expe...,2016.0,2015 10th International Conference on Informat...,NaN,NaN,7459848,NaN,...,NaN,English,"Int. Conf. Inf., Commun. Signal Process., ICICS",Conference paper,Final,NaN,Scopus,2-s2.0-84973636068,q3,Scopus
163,Bhatnagar R.; Sardar S.; Beheshti M.; Podichet...,"Bhatnagar, Roopal (57390567800); Sardar, Saksh...",57390567800; 57208109642; 35752962700; 5521654...,How can natural language processing help model...,2022.0,JAMIA Open,5,2.0,ooac043,NaN,...,NaN,English,JAMIA Open,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85134911178,q3,Scopus

### Final characteristics selected

In [21]:
cols=final.columns.tolist()
cols_df = pd.DataFrame()
cols_df['characteristics'] = cols
display(cols_df)

                  characteristics
0                         authors
1               author full names
2                    author(s) id
3                           title
4                            year
5                    source title
6                          volume
7                           issue
8                        art. no.
9                      page start
10                       page end
11                     page count
12                       cited by
13                            doi
14                           link
15                   affiliations
16      authors with affiliations
17                       abstract
18                author keywords
19                 index keywords
20     molecular sequence numbers
21                  chemicals/cas
22                     tradenames
23                  manufacturers
24                funding details
25                  funding texts
26                     references
27         correspondence address
28                        editors
29                      publisher
30                       sponsors
31                conference name
32                conference date
33            conference location
34                conference code
35                           issn
36                           isbn
37                          coden
38                      pubmed id
39  language of original document
40       abbreviated source title
41                  document type
42              publication stage
43                    open access
44                         source
45                            eid
46                          query
47                  search_engine

In [22]:
cols_df.to_csv("characteristics.csv", encoding="utf-8")

## 3. Peer-review venues 	
The peer-review process is the evaluation of a research paper by experts in the same academic field prior to publication. This ensures that the content is rigorous, valid, original and relevant, helping to maintain the quality and integrity of the scientific literature.

Double-blind is still peer review. In fact, the double-blind review process-where neither the authors nor the reviewers know the identity of the other-is implemented to minimize bias. In addition, having at least three reviewers is usually a common practice to ensure a more complete and rigorous evaluation of the work.

In the single-blind review process, the authors do not know who the reviewers are, but the reviewers do know the identity of the authors. This allows the reviewers to evaluate the work taking into account the author's context, but it can also introduce biases. Despite this, it is still a widely used peer review process in the academic community.

<!-- # peer_review_dict = {
#     "IEEE Conference on Computer Vision and Pattern Recognition (CVPR)": True,
#     "International Conference on Machine Learning (ICML)": True,        
#     "Neural Information Processing Systems (NeurIPS)": True,
#     "Association for Computational Linguistics (ACL)": True,        
#     "Empirical Methods in Natural Language Processing (EMNLP)": True,       
#     "AAAI Conference on Artificial Intelligence": True,        
#     "International Joint Conference on Artificial Intelligence (IJCAI)": True,        
#     "Nature": True,        
#     "PLoS ONE": True,        
#     "LNCS": True,
#     "TOG": True,        
#     "KDD": True,        
#     "arXiv": False  # arXiv no es peer review
# } -->

In [23]:
from pprint import pprint
import re

# 3. Peer-review venues 	
# Nota: analizar conferencias que faltan

def mark_peer_review(conference_name):
    """
    Recibe el nombre de una conferencia y devuelve True si se detecta que es
    una venue peer-reviewed, False en caso contrario.
    La función utiliza el diccionario peer_review_dict para buscar coincidencias
    parciales (ignorando mayúsculas y espacios adicionales).
    """
    # Diccionario original
    peer_review_dict = {
        # Conferencias principales y journals reconocidos
        "CVPR": True, # IEEE/CVF Conference: http://cvpr.thecvf.com/
        "ICML": True, # International Conference on Machine Learning: https://icml.cc/
        "NeurIPS": True, # Conference on Neural Information Processing Systems: https://neurips.cc/
        "ACL": True, # Annual Meeting of the ACL: https://www.aclweb.org/portal/
        "EMNLP": True, # Conference on Empirical Methods in NLP: https://aclanthology.org/venues/emnlp/
        "AAAI": True,  # AAAI Conference on AI: https://aaai.org/conference/
        "IJCAI": True, # International Joint Conference on AI: https://ijcai.org/
        "Nature": True,  # Nature Journal: https://www.nature.com/
        "PLoS ONE": True, # PLoS ONE Journal (for society): https://journals.plos.org/plosone/
        "LNCS": True,  # Lecture Notes in Computer Science (Springer). Springer Lecture Notes: https://link.springer.com/conference/lncs (?)
        "TOG": True,   # ACM Transactions on Graphics. ACM Transactions on Graphics: https://dl.acm.org/journal/tog
        "KDD": True,   # ACM SIGKDD. ACM SIGKDD Conference: https://www.kdd.org/
        
        # Conferencias de tu lista
        "NLPCC": False,   # CCF Conference (China), no es top-tier. CCF NLP Conference: http://tcci.ccf.org.cn/
        "ICEMCE": True,    # IEEE-affiliated (China). IEEE Conference: http://www.icemce.org/
        "ICAICE": True,    # Asumido peer-reviewed (conferencia internacional genérica - China ). International Conference on AI Eng.: http://www.icaice.org/
        "IJCNLP": True,    # Colaboración ACL-Asia. Joint ACL-Asia Conference: https://www.aclweb.org/portal/ijcnlp
        "CCL": True,       # Conferencia nacional china (bajo CCF). Chinese Comp. Ling. Conference: http://cips-cl.org/static/CCL2024/en/index.html

        "SIGIR": True,     # ACM SIGIR (top en Information Retrieval). ACM SIGIR Conference: https://sigir.org/
        "EEKE": True,      # Workshop bajo conferencias principales. Workshop @ JCDL/others: https://eeke-workshop.github.io/
        "COLING": True,    # Conferencia líder en lingüística computacional. Double-blind. International Conference on Comp. Ling.: https://coling2024.org/
        "NNICE": True,     # Asumido peer-reviewed (IEEE/Springer). IEEE Conference: http://www.nnice.org/ (?)
        "Big Data": True,  # IEEE Big Data Conference. IEEE Big Data Conference: http://bigdataieee.org/
        "CompleNet": True, # Conferencia internacional establecida. International Conference: https://complenet.weebly.com (?)
        "RANLP": True,     # Reconocida en NLP (Bulgaria). Recent Advances in NLP: https://ranlp.org/
        "MLNLP": True,     # Conferencia genérica (peer-reviewed típico). Machine Learning & NLP Conf.: https://ieeexplore.ieee.org/xpl/conhome/10799945/proceeding
        "ADMA": True,      # Springer LNCS proceedings. Advanced Data Mining Conf.: https://adma2023.org/
        
        # Plataformas y otros
        "arXiv": False,    # Preprints no revisados. Preprint Repository: https://arxiv.org/
        "NAACL": True,     # Capítulo norteamericano de ACL. NAACL Conference: https://naacl.org/
        "CIKM": True,      # ACM CIKM. ACM CIKM: https://cikm2024.org
        "DASFAA": True,    # Conferencia de bases de datos (Springer). Database Systems Conf.: https://www.dasfaa2024.org/
        "WWW": True,       # The Web Conference. The Web Conference: https://www2024.thewebconf.org/
        "LREC": True,      # Language Resources and Evaluation. Language Resources Conf.: https://lrec-coling-2024.org/
        "ECML": True,      # European Conference on Machine Learning. European Conf. on ML: https://2023.ecmlpkdd.org/
        "KSEM": True,      # Springer proceedings. Knowledge Science Conf.: https://ai-edge.net/index.html
        "IJCNN": True,     # IEEE International Joint Conference on Neural Networks. IEEE Neural Networks Conf.: https://2025.ijcnn.org
        "BIBM": True,      # IEEE Bioinformatics. IEEE Bioinformatics Conf.: https://ieeebibm.org/BIBM2024/
        "FLLM": True,      # Conferencia emergente (asumido peer-reviewed). Foundation & LLM Conf.: https://fllm-conference.org/ (?)
        "WSDM": True,      # ACM WSDM. ACM Web Search Conf.: https://www.wsdm-conference.org/
        "SMC": True,       # IEEE Systems, Man, and Cybernetics. IEEE Systems Conf.: https://ieeesmc2024.org/ 
        "ICICS": True      # IEEE/Springer conference. IEEE ICICS:https://icis2024.aisconferences.org 
}



    # Si no es un string (nan), se devuelve False.
    if not isinstance(conference_name, str):
        return "?"
   
    # Convertir el nombre de la conferencia a minúsculas
    conf_lower = conference_name.lower()
    conf_lower_list = conf_lower.split()
    # print(conf_lower)
    # Recorrer cada clave del diccionario
    for key, is_peer in peer_review_dict.items():
        # Convertir la clave a minúsculas para hacer la comparación
        key_lower = key.lower()
        print(conf_lower_list, key_lower)
        # Si la clave se encuentra en el nombre de la conferencia, devolver el valor asociado.
        if key_lower in conf_lower_list:
            return is_peer # True or false surely

    # Si no se encuentra ninguna coincidencia, se asume que no es peer reviewed
    return "?"

In [24]:
# Ejemplo de uso con tu DataFrame 'final'
# conference_names = final['conference name'].tolist()
# print(len(conference_names))
# print(conference_names)


# for i in conference_names:
#     # print(i)
#     a = mark_peer_review(i)
#     print(a)
#     print('*'*50)

In [25]:
# Ejemplo de uso con tu DataFrame 'final'
final['peer_review_conference'] = final['conference name'].apply(mark_peer_review)
final['peer_review_publisher'] = final['publisher'].apply(mark_peer_review)
final['peer_review_abbreviation'] = final['abbreviated source title'].apply(mark_peer_review)

# Mostrar algunas filas para comprobar el resultado
# print(final[['conference name', 'peer_review']].head())

# final_descartado=final[final['peer_review']==False]
# final_doubt=final[final['peer_review']=="?"]
# final_aceptado=final[final['peer_review']==True]

['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] cvpr
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] icml
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] neurips
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] acl
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] emnlp
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] aaai
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] ijcai
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] nature
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] plos one
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] lncs
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] tog
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] kdd
['13th', 'ccf', 'international', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'chinese', 'computing,', 'nlpcc', '2024'] nlpcc
['2022', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'emnlp', '2022'] cvpr
['2022', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'emnlp', '2022'] icml
['2022', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'emnlp', '2022'] neurips
['2022', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'emnlp', '2022'] acl
['2022', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'emnlp', '2022'] emnlp
['2021', 'conference', 'on', 'empirical', 'methods', 'in', 'natural', 'language', 'processing,', 'emnlp', '2021'] cvpr
['2021', 'conference', 'on', 'empirical', 'methods', 'in', 'natural', 'language', 'processing,', 'emnlp', '2021'] icml
['2021', 'conference', 'on', 'empirical', 'methods', 'in', 'natural', 'language', 'processing,', 'emnlp', '2021'] neurips
['2021', 'conference', 'on', 'empirical', 'methods', 'in', 'natural', 'language', 'processing,', 'emnlp', '2021'] acl
['2021', 'conference', 'on', 'empirical', 'methods', 'in', 'natural', 'language', 'processing,', 'emnlp', '2021'] emnlp
['38th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2024'] cvpr
['38th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2024'] icml
['38th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2024'] neurips
['38th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2024'] acl
['38th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2024'] emnlp
['38th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2024'] aaai
['37th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2023'] cvpr
['37th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2023'] icml
['37th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2023'] neurips
['37th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2023'] acl
['37th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2023'] emnlp
['37th', 'aaai', 'conference', 'on', 'artificial', 'intelligence,', 'aaai', '2023'] aaai
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] cvpr
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] icml
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] neurips
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] acl
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] emnlp
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] aaai
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] ijcai
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] nature
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] plos one
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] lncs
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] tog
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] kdd
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] nlpcc
['7th', 'international', 'conference', 'on', 'electrical,', 'mechanical', 'and', 'computer', 'engineering,', 'icemce', '2023'] icemce
['61st', 'annual', 'meeting', 'of', 'the', 'association', 'for', 'computational', 'linguistics,', 'acl', '2023'] cvpr
['61st', 'annual', 'meeting', 'of', 'the', 'association', 'for', 'computational', 'linguistics,', 'acl', '2023'] icml
['61st', 'annual', 'meeting', 'of', 'the', 'association', 'for', 'computational', 'linguistics,', 'acl', '2023'] neurips
['61st', 'annual', 'meeting', 'of', 'the', 'association', 'for', 'computational', 'linguistics,', 'acl', '2023'] acl
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] cvpr
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] icml
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] neurips
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] acl
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] emnlp
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] aaai
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] ijcai
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] nature
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] plos one
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] lncs
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] tog
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] kdd
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] nlpcc
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] icemce
['5th', 'international', 'conference', 'on', 'artificial', 'intelligence', 'and', 'computer', 'engineering,', 'icaice', '2024'] icaice
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] cvpr
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] icml
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] neurips
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] acl
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] emnlp
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] aaai
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] ijcai
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] nature
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] plos one
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] lncs
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] tog
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] kdd
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] nlpcc
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] icemce
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] icaice
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] ijcnlp
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] ccl
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] sigir
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] eeke
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] coling
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] nnice
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] big data
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] complenet
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] ranlp
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] mlnlp
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] adma
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] arxiv
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] naacl
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] cikm
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] dasfaa
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] www
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] lrec
['13th', 'international', 'joint', 'conference', 'on', 'natural', 'language', 'processing', 'and', 'the', '3rd', 'conference', 'of', 'the', 'asia-pacific', 'chapter', 'of', 'the', 'association', 'for', 'computational', 'linguistics:', 'findings', 'of', 'the', 'association', 'for', 'computational', 'linguistic,', 'ijcnlp-aacl', '2023'] ecml

In [26]:
# display(final_aceptado)

In [27]:
# display(final_doubt)

In [28]:
# display(final_descartado)

In [29]:
import pandas as pd

# Suponiendo que tu DataFrame se llama df
conteo = final['peer_review_conference'].value_counts()
print(conteo)

peer_review_conference
?        71
True     63
False     1
Name: count, dtype: int64

In [30]:
import pandas as pd

# Suponiendo que tu DataFrame se llama df
conteo = final['peer_review_publisher'].value_counts()
print(conteo)

peer_review_publisher
?       132
True      3
Name: count, dtype: int64

In [31]:
import pandas as pd

# Suponiendo que tu DataFrame se llama df
conteo = final['peer_review_abbreviation'].value_counts()
print(conteo)

peer_review_abbreviation
?       94
True    41
Name: count, dtype: int64

After this automatic phase, I performed a manual filter to select those that the system could not select.

## 4. Full text available
Due to selected papers are from scopus, there is no way to find out if they are full available althought I search them each within this platflorm

## 5. Free access
It is true that i have a column call open acces but not all papers in the metata excel have a value on there. After checking if any of that ones that do not have nothing had access or not, i realize that simply scopus metadata is not fullfilled. Same happens to DOI ids.

In [ ]:
final.to_csv("summary_reduced.csv", encoding="utf-8")