# Scopus

In [ ]:
import os
import pandas as pd


queries_path = "./re_te_lowresources/queries.csv"

df = pd.read_csv(queries_path)
df.head()

In [ ]:
queries = df["Query String"]
print(queries)

In [ ]:
import pandas as pd

# Suponiendo que la columna "Description" contiene cadenas como:
# "Relation Extraction, Low-resource"
terms = df["Description"].tolist()

# Dividir cada descripción en dos términos y eliminar espacios extra
pairs = [tuple(map(str.strip, term.split(','))) for term in terms if ',' in term]

# Crear el DataFrame con dos columnas a partir de la lista de tuplas
terms_df = pd.DataFrame(pairs, columns=["term1", "term2"])

display(terms_df)

In [ ]:
!pip install pybliometrics

In [ ]:
import pybliometrics

# Para ver donde esta la configuracion
pybliometrics.scopus.utils.constants.CONFIG_FILE

Tras la instalación, normalmente pybliometrics genera un archivo de configuración en tu carpeta de usuario. En sistemas tipo UNIX (Linux/Mac), suele ser `~/.pybliometrics/config.ini`.

https://pybliometrics.readthedocs.io/en/stable/configuration.html

In [ ]:
import pybliometrics

pybliometrics.scopus.init() 

# Creating config file at /Users/jpardo/.config/pybliometrics.cfg with default paths...

# A

In [ ]:
from pybliometrics.scopus import ScopusSearch

# Hacer queries

for _, row in terms_df.iterrows():
    # print(row["term1"])
    query = f"TITLE-ABS-KEY('{row['term1'].lower()}' AND '{row['term2'].lower()}') AND PUBYEAR > 2015"
    print(f"Query: {query}")
    
    s = ScopusSearch(query)
    print(f"Number of results: {len(s.results)}")

# B

In [ ]:
from pybliometrics.scopus import ScopusSearch

# Hacer queries
for _, row in terms_df.iterrows():
    query = f"TITLE({row['term1'].lower()}) AND ABS({row['term2'].lower()}) AND PUBYEAR > 2015"
    s = ScopusSearch(query)
    
    print(f"Query: {query}")
    if len(s.results)>0:
        print(f"Number of results: {len(s.results)}")

# Manual

In [2]:
import os 
import pandas as pd

def load_all_datasets(main_path, queque, dataset):
    scopus = pd.DataFrame()
    que = os.listdir(main_path)
    for i in que:
        # Saltar elementos que terminen en .csv o .ipynb o sean ".DS_Store"
        if i.endswith('.csv') or i.endswith('.ipynb') or i == ".DS_Store" or i in queque:
            continue
        p = os.path.join(main_path, i)
        que2 = os.listdir(p)
        for a in que2:
            if a.endswith('.csv') or a.endswith('.ipynb') or a == ".DS_Store":
                continue
            dat = os.path.join(p, a)
            que3 = os.listdir(dat)
            if que3:
                ar = os.path.join(dat, dataset)
                if dataset.endswith(".xls"):
                    r = pd.read_excel(ar, engine="xlrd")
                    r["query"]=i
                else:
                    r = pd.read_csv(ar)
                    r["query"]=i
                scopus = pd.concat([scopus, r], ignore_index=True)
    return scopus

In [ ]:
# Ejemplo de uso:
main_path = "./" #/scopus
scopus = load_all_datasets(main_path, queque=[], dataset= "scopus.csv")
display(scopus)

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID,query
0,Ariyanto A.D.P.; Purwitasari D.; Fatichah C.,"Ariyanto, Amelia Devi Putri (57563530700); Pur...",57563530700; 23493277700; 35811948800,A Systematic Review on Semantic Role Labeling ...,2024,IEEE Access,12,NaN,NaN,57917.0,...,NaN,NaN,English,IEEE Access,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85191327866,q31
1,Bhavya B.; Isaza P.T.; Deng Y.; Nidd M.; Azad ...,"Bhavya, Bhavya (57224636404); Isaza, Paulina T...",57224636404; 57201772538; 55459372100; 6507158...,Exploring Large Language Models for Low-Resour...,2023,IEEE International Conference on Data Mining W...,NaN,NaN,NaN,1203.0,...,NaN,NaN,English,"IEEE Int. Conf. Data Mining Workshops, ICDMW",Conference paper,Final,NaN,Scopus,2-s2.0-85186140312,q31
2,Zhou B.; Zhang Y.; Song K.; Wang H.; Zhao Y.; ...,"Zhou, Baohang (57221050137); Zhang, Ying (5595...",57221050137; 55954386400; 57195330120; 5722110...,MCIL: Multimodal Counterfactual Instance Learn...,2024,2024 Joint International Conference on Computa...,NaN,NaN,NaN,11101.0,...,NaN,NaN,English,"Jt. Int. Conf. Comput. Linguist., Lang. Resour...",Conference paper,Final,NaN,Scopus,2-s2.0-85195897477,q31
3,Cai E.; Simek O.; Miller B.A.; Sullivan D.; Yo...,"Cai, Erica (57909147300); Simek, Olga (6507045...",57909147300; 6507045650; 57207151897; 58996568...,From Low Resource Information Extraction to Id...,2024,Springer Proceedings in Complexity,NaN,NaN,NaN,15.0,...,NaN,NaN,English,Springer Proc. Complex.,Conference paper,Final,NaN,Scopus,2-s2.0-85191021750,q31
4,Li T.; Wang Z.; Li Z.,"Li, Tongliang (57222531333); Wang, Zixiang (59...",57222531333; 59293797500; 56024684400,Low Resource Quantitative Information Extracti...,2023,Proceedings of the 37th AAAI Conference on Art...,37,NaN,NaN,13112.0,...,NaN,NaN,English,"Proc. AAAI Conf. Artif. Intell., AAAI",Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85168013529,q31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,Sachan M.; Dubey A.; Mitchell T.; Roth D.; Xin...,"Sachan, Mrinmaya (36094978300); Dubey, Avinava...",36094978300; 36016208000; 7402175019; 74016690...,Learning pipelines with limited data and domai...,2018,Advances in Neural Information Processing Systems,2018-December,NaN,NaN,140.0,...,NaN,NaN,English,Adv. neural inf. proces. syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85064808357,q3
475,Stickley D.,"Stickley, Daniel (57224354310)",57224354310,Relating relations: Meta-relation extraction f...,2021,EACL 2021 - 16th Conference of the European Ch...,NaN,NaN,NaN,129.0,...,NaN,NaN,English,EACL - Conf. Eur. Chapter Assoc. Comput. Lingu...,Conference paper,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85107459083,q3
476,Peng D.; Pei Z.; Mo D.,"Peng, Da (57221682382); Pei, Zhongmin (3559044...",57221682382; 35590446700; 58244228500,MTL-JER: Meta-Transfer Learning for Low-Resour...,2023,2023 3rd International Conference on Neural Ne...,NaN,NaN,NaN,78.0,...,NaN,NaN,English,"Int. Conf. Neural Networks, Inf. Commun. Eng.,...",Conference paper,Final,NaN,Scopus,2-s2.0-85159024362,q3
477,Yang X.; Mao K.; Zhao R.,"Yang, Xuefeng (56194089500); Mao, Kezhi (70064...",56194089500; 7006403609; 56717092800,Distributional sentence representation by expe...,2016,2015 10th International Conference on Informat...,NaN,NaN,7459848,NaN,...,NaN,NaN,English,"Int. Conf. Inf., Commun. Signal Process., ICICS",Conference paper,Final,NaN,Scopus,2-s2.0-84973636068,q3
478,Bhatnagar R.; Sardar S.; Beheshti M.; Podichet...,"Bhatnagar, Roopal (57390567800); Sardar, Saksh...",57390567800; 57208109642; 35752962700; 5521654...,How can natural language processing help model...,2022,JAMIA Open,5,2.0,ooac043,NaN,...,NaN,NaN,English,JAMIA Open,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85134911178,q3

In [4]:
import pandas as pd

# Supón que ya tienes el DataFrame 'df'
initial_rows = scopus.shape[0]  # Número de filas inicial

# Eliminar filas duplicadas (puedes usar inplace=True para modificar el mismo DataFrame)
scopus_final = scopus.drop_duplicates()

final_rows = scopus_final.shape[0]  # Número de filas después de eliminar duplicados

filas_eliminadas = initial_rows - final_rows

print(f"Se han eliminado {filas_eliminadas} filas duplicadas.")
scopus_final.to_csv(os.path.join(main_path, "scopus.csv"))

Se han eliminado 33 filas duplicadas.

In [ ]:
# Ejemplo de uso:
main_path = "./" #/scopus
scopus = load_all_datasets(main_path, queque=['q31','q32','q33','q34','q46','q47','q48','q49','q61','q62','q63','q64'], dataset= "scopus.csv")
display(scopus)

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID,query
0,Zhong J.; Liu Y.; Ouyang C.; Ren L.; Zhu C.; H...,"Zhong, Jin (59423140700); Liu, Yongbin (564967...",59423140700; 56496782000; 35226676500; 5826517...,CouBRE: Counterfactual NLI For Low-Resource Bi...,2025,Lecture Notes in Computer Science (including s...,15360 LNAI,NaN,NaN,109.0,...,NaN,NaN,English,Lect. Notes Comput. Sci.,Conference paper,Final,NaN,Scopus,2-s2.0-85210083717,q1
1,Xu X.; Chen X.; Zhang N.; Xie X.; Chen X.; Che...,"Xu, Xin (57421213500); Chen, Xiang (5915764150...",57421213500; 59157641500; 55923601900; 5722237...,Towards Realistic Low-resource Relation Extrac...,2022,Findings of the Association for Computational ...,NaN,NaN,NaN,413.0,...,NaN,NaN,English,Find. Assoc. Comput. Linguist.: EMNLP,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85149872682,q1
2,Dong M.; Pan C.; Luo Z.,"Dong, Manqing (57202994996); Pan, Chunguang (5...",57202994996; 57223040498; 57210633943,MapRE: An Effective Semantic Mapping Approach ...,2021,EMNLP 2021 - 2021 Conference on Empirical Meth...,NaN,NaN,NaN,2694.0,...,NaN,NaN,English,EMNLP - Conf. Empir. Methods Nat. Lang. Proces...,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85127414858,q1
3,Yu J.; Wang X.; Chen W.,"Yu, Junjie (57189380183); Wang, Xing (55978420...",57189380183; 55978420400; 55715988100,Reliable Data Generation and Selection for Low...,2024,Proceedings of the AAAI Conference on Artifici...,38,17.0,NaN,19440.0,...,NaN,NaN,English,Proc. AAAI Conf. Artif. Intell.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85189627963,q1
4,Wang P.; Shao T.; Ji K.; Li G.; Ke W.,"Wang, Peng (56182131700); Shao, Tong (57340534...",56182131700; 57340534200; 58339210600; 5734716...,fmLRE: A Low-Resource Relation Extraction Mode...,2023,Proceedings of the 37th AAAI Conference on Art...,37,NaN,NaN,13700.0,...,NaN,NaN,English,"Proc. AAAI Conf. Artif. Intell., AAAI",Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85167973559,q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Sachan M.; Dubey A.; Mitchell T.; Roth D.; Xin...,"Sachan, Mrinmaya (36094978300); Dubey, Avinava...",36094978300; 36016208000; 7402175019; 74016690...,Learning pipelines with limited data and domai...,2018,Advances in Neural Information Processing Systems,2018-December,NaN,NaN,140.0,...,NaN,NaN,English,Adv. neural inf. proces. syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85064808357,q3
200,Stickley D.,"Stickley, Daniel (57224354310)",57224354310,Relating relations: Meta-relation extraction f...,2021,EACL 2021 - 16th Conference of the European Ch...,NaN,NaN,NaN,129.0,...,NaN,NaN,English,EACL - Conf. Eur. Chapter Assoc. Comput. Lingu...,Conference paper,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85107459083,q3
201,Peng D.; Pei Z.; Mo D.,"Peng, Da (57221682382); Pei, Zhongmin (3559044...",57221682382; 35590446700; 58244228500,MTL-JER: Meta-Transfer Learning for Low-Resour...,2023,2023 3rd International Conference on Neural Ne...,NaN,NaN,NaN,78.0,...,NaN,NaN,English,"Int. Conf. Neural Networks, Inf. Commun. Eng.,...",Conference paper,Final,NaN,Scopus,2-s2.0-85159024362,q3
202,Yang X.; Mao K.; Zhao R.,"Yang, Xuefeng (56194089500); Mao, Kezhi (70064...",56194089500; 7006403609; 56717092800,Distributional sentence representation by expe...,2016,2015 10th International Conference on Informat...,NaN,NaN,7459848,NaN,...,NaN,NaN,English,"Int. Conf. Inf., Commun. Signal Process., ICICS",Conference paper,Final,NaN,Scopus,2-s2.0-84973636068,q3
203,Bhatnagar R.; Sardar S.; Beheshti M.; Podichet...,"Bhatnagar, Roopal (57390567800); Sardar, Saksh...",57390567800; 57208109642; 35752962700; 5521654...,How can natural language processing help model...,2022,JAMIA Open,5,2.0,ooac043,NaN,...,NaN,NaN,English,JAMIA Open,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85134911178,q3

In [6]:
import pandas as pd

# Supón que ya tienes el DataFrame 'df'
initial_rows = scopus.shape[0]  # Número de filas inicial

# Eliminar filas duplicadas (puedes usar inplace=True para modificar el mismo DataFrame)
scopus_final = scopus.drop_duplicates(subset='Title', keep='first')
# scopus_final = scopus.drop_duplicates()

final_rows = scopus_final.shape[0]  # Número de filas después de eliminar duplicados

filas_eliminadas = initial_rows - final_rows

print(f"Se han eliminado {filas_eliminadas} filas duplicadas.")
scopus_final.to_csv(os.path.join(main_path, "scopus_reducido.csv"))

Se han eliminado 40 filas duplicadas.

In [7]:
display(scopus_final)

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID,query
0,Zhong J.; Liu Y.; Ouyang C.; Ren L.; Zhu C.; H...,"Zhong, Jin (59423140700); Liu, Yongbin (564967...",59423140700; 56496782000; 35226676500; 5826517...,CouBRE: Counterfactual NLI For Low-Resource Bi...,2025,Lecture Notes in Computer Science (including s...,15360 LNAI,NaN,NaN,109.0,...,NaN,NaN,English,Lect. Notes Comput. Sci.,Conference paper,Final,NaN,Scopus,2-s2.0-85210083717,q1
1,Xu X.; Chen X.; Zhang N.; Xie X.; Chen X.; Che...,"Xu, Xin (57421213500); Chen, Xiang (5915764150...",57421213500; 59157641500; 55923601900; 5722237...,Towards Realistic Low-resource Relation Extrac...,2022,Findings of the Association for Computational ...,NaN,NaN,NaN,413.0,...,NaN,NaN,English,Find. Assoc. Comput. Linguist.: EMNLP,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85149872682,q1
2,Dong M.; Pan C.; Luo Z.,"Dong, Manqing (57202994996); Pan, Chunguang (5...",57202994996; 57223040498; 57210633943,MapRE: An Effective Semantic Mapping Approach ...,2021,EMNLP 2021 - 2021 Conference on Empirical Meth...,NaN,NaN,NaN,2694.0,...,NaN,NaN,English,EMNLP - Conf. Empir. Methods Nat. Lang. Proces...,Conference paper,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85127414858,q1
3,Yu J.; Wang X.; Chen W.,"Yu, Junjie (57189380183); Wang, Xing (55978420...",57189380183; 55978420400; 55715988100,Reliable Data Generation and Selection for Low...,2024,Proceedings of the AAAI Conference on Artifici...,38,17.0,NaN,19440.0,...,NaN,NaN,English,Proc. AAAI Conf. Artif. Intell.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85189627963,q1
4,Wang P.; Shao T.; Ji K.; Li G.; Ke W.,"Wang, Peng (56182131700); Shao, Tong (57340534...",56182131700; 57340534200; 58339210600; 5734716...,fmLRE: A Low-Resource Relation Extraction Mode...,2023,Proceedings of the 37th AAAI Conference on Art...,37,NaN,NaN,13700.0,...,NaN,NaN,English,"Proc. AAAI Conf. Artif. Intell., AAAI",Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85167973559,q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,Gao F.; Song X.; Gu J.; Zhang L.; Liu Y.; Zhan...,"Gao, Feng (50061267800); Song, Xuren (58303593...",50061267800; 58303593500; 8311080000; 57249181...,Fine-Grained Relation Extraction for Drug Inst...,2023,IEEE Access,11,NaN,NaN,51777.0,...,NaN,NaN,English,IEEE Access,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85160999982,q3
199,Sachan M.; Dubey A.; Mitchell T.; Roth D.; Xin...,"Sachan, Mrinmaya (36094978300); Dubey, Avinava...",36094978300; 36016208000; 7402175019; 74016690...,Learning pipelines with limited data and domai...,2018,Advances in Neural Information Processing Systems,2018-December,NaN,NaN,140.0,...,NaN,NaN,English,Adv. neural inf. proces. syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85064808357,q3
200,Stickley D.,"Stickley, Daniel (57224354310)",57224354310,Relating relations: Meta-relation extraction f...,2021,EACL 2021 - 16th Conference of the European Ch...,NaN,NaN,NaN,129.0,...,NaN,NaN,English,EACL - Conf. Eur. Chapter Assoc. Comput. Lingu...,Conference paper,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85107459083,q3
202,Yang X.; Mao K.; Zhao R.,"Yang, Xuefeng (56194089500); Mao, Kezhi (70064...",56194089500; 7006403609; 56717092800,Distributional sentence representation by expe...,2016,2015 10th International Conference on Informat...,NaN,NaN,7459848,NaN,...,NaN,NaN,English,"Int. Conf. Inf., Commun. Signal Process., ICICS",Conference paper,Final,NaN,Scopus,2-s2.0-84973636068,q3
203,Bhatnagar R.; Sardar S.; Beheshti M.; Podichet...,"Bhatnagar, Roopal (57390567800); Sardar, Saksh...",57390567800; 57208109642; 35752962700; 5521654...,How can natural language processing help model...,2022,JAMIA Open,5,2.0,ooac043,NaN,...,NaN,NaN,English,JAMIA Open,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85134911178,q3